/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/track.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/track.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Street003_-_applied_transform'].geometry} material={nodes['Street003_-_applied_transform'].material} />
    </group>
  )
}

useGLTF.preload('/track.glb')
